### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by brekJ** [brekJ/gh-flow-practice#2]
## Tasks 

- [x] Print fizz, If i is multiple of 3.
- [x] Print buzz, If i is multiple of 5.
- [ ] Print fizzbuzz, If i is multiple of 15.
- [x] Otherwise, print i itself.

## References

- [Fizzbuzz wikipedia](https://en.wikipedia.org/wiki/Fizz_buzz)
